// ========================================
// BU Calculator — PDF Export Utility
// ========================================

import type { SemesterEvaluation, LatinHonorsEvaluation, Subject, Semester, HonorsRules } from '../types';
import { formatGWA, getGradeLabel } from './bu-computation';
import { jsPDF } from 'jspdf';

// ----------------------------------------
// Semester Honors PDF (Tool A)
// ----------------------------------------

export function exportSemesterPDF(
  subjects: Subject[],
  evaluation: SemesterEvaluation
): void {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Bicol University', margin, y);
  y += 8;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Semester GWA Report', margin, y);
  y += 12;

  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, 190, y);
  y += 10;

  // GWA Result
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`GWA: ${formatGWA(evaluation.gwaResult.gwa)}`, margin, y);
  y += 7;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Status: ${evaluation.honorLabel}`, margin, y);
  y += 5;
  doc.text(
    `Total Academic Units: ${evaluation.gwaResult.totalAcademicUnits}`,
    margin,
    y
  );
  y += 5;
  doc.text(
    `Total Weighted Grades: ${evaluation.gwaResult.totalWeightedGrades.toFixed(1)}`,
    margin,
    y
  );
  y += 12;

  // Subject table header
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Subject', margin, y);
  doc.text('Units', 90, y);
  doc.text('Grade', 115, y);
  doc.text('Rating', 140, y);
  doc.text('PE/NSTP', 170, y);
  y += 3;
  doc.line(margin, y, 190, y);
  y += 5;

  // Subject rows
  doc.setFont('helvetica', 'normal');
  const academicSubjects = subjects.filter((s) => s.grade !== '');
  for (const subject of academicSubjects) {
    if (y > 270) {
      doc.addPage();
      y = margin;
    }

    doc.text(subject.subjectCode || '(No code)', margin, y);
    doc.text(String(subject.units), 90, y);
    doc.text(String(subject.grade), 115, y);
    if (typeof subject.grade === 'number' && subject.grade !== 5.0) {
      doc.text(getGradeLabel(subject.grade), 140, y);
    } else {
      doc.text(getGradeLabel(subject.grade as any), 140, y);
    }
    doc.text(subject.isPeNstp ? 'Yes' : 'No', 170, y);
    y += 6;
  }

  // Footer
  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by BU Calculator — ${new Date().toLocaleDateString()}`,
    margin,
    y
  );

  doc.save('BU-Semester-GWA-Report.pdf');
}

// ----------------------------------------
// Cumulative Latin Honors PDF (Tool B)
// ----------------------------------------

export function exportCumulativePDF(
  semesters: Semester[],
  evaluation: LatinHonorsEvaluation,
  _rules: HonorsRules
): void {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Bicol University', margin, y);
  y += 8;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Cumulative GWA Report — Latin Honors', margin, y);
  y += 12;

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, 190, y);
  y += 10;

  // Cumulative result
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Cumulative GWA: ${formatGWA(evaluation.gwaResult.gwa)}`, margin, y);
  y += 7;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Status: ${evaluation.honorLabel}`, margin, y);
  y += 5;
  doc.text(
    `Total Academic Units: ${evaluation.gwaResult.totalAcademicUnits}`,
    margin,
    y
  );
  y += 12;

  // Semester summaries
  for (const summary of evaluation.semesterSummaries) {
    if (y > 250) {
      doc.addPage();
      y = margin;
    }

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(summary.semesterName, margin, y);
    y += 6;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`GWA: ${formatGWA(summary.gwa)}`, margin + 4, y);
    doc.text(`Units: ${summary.totalUnits}`, 80, y);
    doc.text(`Subjects: ${summary.subjectCount}`, 120, y);
    if (summary.hasIssues) {
      doc.setTextColor(220, 50, 50);
      doc.text('⚠ Has disqualifying grades', 155, y);
      doc.setTextColor(0, 0, 0);
    }
    y += 5;

    // Individual subjects for this semester
    const semester = semesters.find((s) => s.id === summary.semesterId);
    if (semester) {
      for (const subject of semester.subjects.filter((s) => s.grade !== '')) {
        if (y > 270) {
          doc.addPage();
          y = margin;
        }
        doc.setFontSize(8);
        doc.text(
          `   ${subject.subjectCode || '(No code)'} — ${subject.units}u — ${subject.grade}${subject.isPeNstp ? ' (PE/NSTP)' : ''}`,
          margin + 4,
          y
        );
        y += 4;
      }
    }
    y += 6;
  }

  // Footer
  y += 5;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by BU Calculator — ${new Date().toLocaleDateString()}`,
    margin,
    y
  );

  doc.save('BU-Cumulative-GWA-Report.pdf');
}
