// ========================================
// BU Calculator — PDF Export Utility
// ========================================

import type { SemesterEvaluation, LatinHonorsEvaluation, Subject, Semester, HonorsRules } from '../types';
import { formatGWA, getGradeLabel } from './bu-computation';
import { jsPDF } from 'jspdf';

// ----------------------------------------
// Semester Honors PDF (Tool A)
// ----------------------------------------

export function exportSemesterPDF(
  subjects: Subject[],
  evaluation: SemesterEvaluation,
  userName: string
): void {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;
  
  // Custom colors
  const primaryColor = [22, 101, 52]; // forest-800
  const secondaryColor = [63, 98, 18]; // sage-700
  const textColor = [51, 65, 85]; // slate-700
  const lightGray = [241, 245, 249];

  // Header Block (Colored)
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('BICOL UNIVERSITY', margin, 22);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('SEMESTER GWA REPORT', margin, 30);
  
  y = 50;
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);

  // Student Info Box
  if (userName) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Student Name: ${userName}`, margin, y);
    y += 10;
  }

  // Result Summary Box
  doc.setFillColor(lightGray[0], lightGray[1], lightGray[2]);
  doc.rect(margin, y, 170, 35, 'F');
  
  y += 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`General Weighted Average (GWA): ${formatGWA(evaluation.gwaResult.gwa)}`, margin + 5, y);
  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Academic Units: ${evaluation.gwaResult.totalAcademicUnits}`, margin + 5, y);
  y += 8;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.text(`Status: ${evaluation.honorLabel || 'No Honors'}`, margin + 5, y);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);

  y += 20;

  // Subject table header
  doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.rect(margin, y - 5, 170, 10, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Subject', margin + 2, y + 1);
  doc.text('Units', 90, y + 1);
  doc.text('Grade', 115, y + 1);
  doc.text('Rating', 140, y + 1);
  doc.text('NSTP Subject', 160, y + 1);
  y += 8;
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);

  // Subject rows
  doc.setFont('helvetica', 'normal');
    const academicSubjects = subjects.filter((s) => s.grade !== '');
    let isAlt = false;
    for (const subject of academicSubjects) {
    if (y > 270) {
      doc.addPage();
      y = margin;
    }
    
    if (isAlt) {
      doc.setFillColor(lightGray[0], lightGray[1], lightGray[2]);
      doc.rect(margin, y - 5, 170, 8, 'F');
    }
    isAlt = !isAlt;

    doc.text(subject.subjectCode || '(No code)', margin + 2, y);
    doc.text(String(subject.units), 90, y);
    doc.text(String(subject.grade), 115, y);
    if (typeof subject.grade === 'number' && subject.grade !== 5.0) {
      doc.text(getGradeLabel(subject.grade), 140, y);
    } else {
      doc.text(getGradeLabel(subject.grade as any), 140, y);
    }
    doc.text(subject.isNstp ? 'Yes' : 'No', 170, y);
    y += 8;
  }

  // Footer
  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by BU Calculator — ${new Date().toLocaleDateString()}`,
    margin,
    y
  );

  doc.save('BU-Semester-GWA-Report.pdf');
}

// ----------------------------------------
// Cumulative Latin Honors PDF (Tool B)
// ----------------------------------------

export function exportCumulativePDF(
  semesters: Semester[],
  evaluation: LatinHonorsEvaluation,
  _rules: HonorsRules,
  userName: string
): void {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;

  // Custom colors
  const primaryColor = [22, 101, 52];
  const secondaryColor = [63, 98, 18];
  const textColor = [51, 65, 85];
  const lightGray = [241, 245, 249];

  // Header Block (Colored)
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('BICOL UNIVERSITY', margin, 22);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('LATIN HONORS REPORT', margin, 30);
  
  y = 50;
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);

  // Student Info Box
  if (userName) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Student Name: ${userName}`, margin, y);
    y += 10;
  }

  // Result Summary Box
  doc.setFillColor(lightGray[0], lightGray[1], lightGray[2]);
  doc.rect(margin, y, 170, 35, 'F');
  
  y += 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Cumulative GWA: ${formatGWA(evaluation.gwaResult.gwa)}`, margin + 5, y);
  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Academic Units: ${evaluation.gwaResult.totalAcademicUnits}`, margin + 5, y);
  y += 8;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.text(`Status: ${evaluation.honorLabel || 'No Honors'}`, margin + 5, y);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);

  y += 20;

  // Semester summaries
  for (const summary of evaluation.semesterSummaries) {
    if (y > 250) {
      doc.addPage();
      y = margin;
    }

    doc.setFillColor(lightGray[0], lightGray[1], lightGray[2]);
    doc.rect(margin, y - 5, 170, 12, 'F');
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(summary.semesterName, margin + 2, y + 2);
    y += 10;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`GWA: ${formatGWA(summary.gwa)}`, margin + 4, y);
    doc.text(`Units: ${summary.totalUnits}`, 80, y);
    doc.text(`Subjects: ${summary.subjectCount}`, 120, y);
    if (summary.hasIssues) {
      doc.setTextColor(220, 50, 50);
      doc.text('⚠ Has disqualifying grades', 155, y);
      doc.setTextColor(0, 0, 0);
    }
    y += 5;

    // Individual subjects for this semester
    const semester = semesters.find((s) => s.id === summary.semesterId);
    if (semester) {
      for (const subject of semester.subjects.filter((s) => s.grade !== '')) {
        if (y > 270) {
          doc.addPage();
          y = margin;
        }
        doc.setFontSize(8);
        doc.text(
          `   ${subject.subjectCode || '(No code)'} — ${subject.units}u — ${subject.grade}${subject.isNstp ? ' (NSTP)' : ''}`,
          margin + 4,
          y
        );
        y += 4;
      }
    }
    y += 6;
  }

  // Footer
  y += 5;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by BU Calculator — ${new Date().toLocaleDateString()}`,
    margin,
    y
  );

  doc.save('BU-Cumulative-GWA-Report.pdf');
}
